added fpcc driver

diff --git a/fpcc-diff b/fpcc-diff
--- a/fpcc-diff
+++ b/fpcc-diff
@@ -15,16 +15,36 @@ SIDEBYSIDE=0
 # number of lines before and after a match
 CONTEXT=2
 
+function usage {
+  cat <<EOT
+  USAGE: $0 [-y] [target.sig source.sig]
+EOT
+  exit 1
+}
 
-while getopts "y" opt; do
+
+
+while getopts "y" opt
+do
   case $opt in
     y) SIDEBYSIDE=1 ;;
     \?)
-      echo "Invalid option: -$OPTARG" >&2
+      #echo "Invalid option: -$OPTARG" >&2
+      usage
       ;;
   esac
 done
 shift $((OPTIND-1))
+
+
+if [[ $# -eq 2 ]]; then
+  # execute fpcc-map with the two arguments
+  INPUT="$(dirname $(which $0))/fpcc-map $@"
+elif [[ $# -eq 0 ]]; then
+  INPUT="cat -" # input is from stdin
+else
+  usage
+fi
 
 
 # arguments: filename, startline, length
@@ -52,7 +72,7 @@ function section {
 
 
 RE="(.+):([[:digit:]]+),([[:digit:]]+) -- (.+):([[:digit:]]+),([[:digit:]]+)"
-while read line
+${INPUT} | while read line
 do
   if [[ ${line} =~ ${RE} ]]
   then
